apiVersion: apps/v1
kind: Deployment
metadata: 
	name: catalog-deploy
spec: 
	selector:
		matchLabels:
			app: catalog-pod
	replicas: 1
	template: 
		metadata:
			labels:
				app: catalog-pod
		spec: 
			imagePullSecrets:
			- name: acr-secret
			containers:
			- name: catalog-conatainer 
			  image: catalogservice20221201152530.azurecr.io/catalogservice:latest
			  imagePullPolicy: Always
			  resources:
			  env: 
				- name: DB_CONNECTION
				  value: SQL connection string here.
			  ports: 
			  - containerPort: 80

---

apiVersion: v1
kind: Service
metadata: 
	name: catalog-service
spec: 
	selector: 
		app: catalog-pod
	type: LoadBalancer
	ports: 
	- port: 80
	  targetPort: 80